/** @format */

import Head from "next/head";
import Image from "next/image";
import Banner from "../componrnts/banner/banner";
import NavBar from "../componrnts/nav/Nav";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <NavBar username={"Kwabena@ymail.com"} />
      <Banner
        title={"Breaking Bad"}
        subTitle={"Walter White's Journey"}
        imgUrl={"../public/static/The-Best-Breaking-Bad-Quotes.webp"}
      />
    </div>
  );
}
