/** @format */

import Head from "next/head";
import Image from "next/image";
import Banner from "../componrnts/banner/banner";
import SectionCards from "../componrnts/card/Section-card.component";
import NavBar from "../componrnts/nav/Nav";
import styles from "../styles/Home.module.css";

export default function Home() {
  const DisneyVideos = [
    {
      imgUrl: "/static/The-Best-Breaking-Bad-Quotes.jpg",
    },
    {
      imgUrl: "/static/The-Best-Breaking-Bad-Quotes.jpg",
    },
    {
      imgUrl: "/static/The-Best-Breaking-Bad-Quotes.jpg",
    },
    {
      imgUrl: "/static/The-Best-Breaking-Bad-Quotes.jpg",
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <NavBar username={"Kwabena@ymail.com"} />
      <Banner
        title={"Breaking Bad"}
        subTitle={"Walter White's Journey"}
        imgUrl={"../public/static/The-Best-Breaking-Bad-Quotes.webp"}
      />

      <div className={styles.sectionWrapper}>
        <SectionCards title={"Disney"} videos={DisneyVideos} size={"large"} />
      </div>
    </div>
  );
}
