/** @format */

import Head from "next/head";
import styles from "../styles/Home.module.css";

import Banner from "../componrnts/banner/banner";
import NavBar from "../componrnts/nav/Nav";

import SectionCards from "../componrnts/card/Section-card.component";

import { getPopularVideos, getVideos } from "../lib/videos";
import useRedirectUser from "../utils/redirectUser";

export const getServerSideProps = async (context) => {
  // eslint-disable-next-line
  const { userId, token } = await useRedirectUser(context);

  const disneyVideos = await getVideos("marvel%20official%20trailers");
  const techVideos = await getVideos("tech");
  const travelVideos = await getVideos("travel");
  const PopularVideos = await getPopularVideos();
  // const PopularVideos = await getVideos("vevo");
  return {
    props: {
      disneyVideos,
      techVideos,
      travelVideos,
      PopularVideos,
    },
  };
};

export default function Home({
  disneyVideos,
  techVideos,
  travelVideos,
  PopularVideos,
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className={styles.main}>
        <NavBar username={"Kwabena@ymail.com"} />
        <Banner
          videoId='1JLUn2DFW4w'
          title={"Breaking Bad"}
          subTitle={"Walter White's Journey"}
          imgUrl={"../public/static/The-Best-Breaking-Bad-Quotes.webp"}
        />

        <div className={styles.sectionWrapper}>
          <SectionCards title={"Marvel"} videos={disneyVideos} size={"large"} />
          <SectionCards
            title={"Travel"}
            videos={travelVideos}
            size={"medium"}
          />
          <SectionCards title={"Tech"} videos={techVideos} size={"small"} />
          <SectionCards
            title={"Popular"}
            videos={PopularVideos}
            size={"small"}
          />
        </div>
      </div>
    </div>
  );
}
